services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: unipascohub
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d unipascohub']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  postgres-data:
